---
- name: Provision wellknown server container image
  hosts: packer

  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../../../ryo-control-node/configuration/configuration.yml"
    # Host configuration
    - "{{ playbook_dir }}/../../../ryo-host/configuration/configuration_{{ host_id }}.yml"
    # Module configuration
    - "{{ playbook_dir }}/../../configuration/configuration.yml"

  roles:
    - role: upgrade-container
    - role: install-iptables
    - role: install-consul
    - role: install-unzip
    - role: install-consul-template
    - role: install-nginx
    - role: set-up-firewall
    - role: set-up-consul
    - role: set-up-wellknown
    - role: set-up-consul-template
