---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

# Note: nginx configuration is generated dynamically by consul-template

# Copy wellknown-services consul service configuration file
#
- name: Copy wellknown-services consul service configuration file
  copy:
    mode: 0640
    owner: consul
    group: consul
    dest: /etc/consul.d/wellknown-services.hcl
    src: wellknown-services.hcl
    force: yes
