---
## The generic directory /var/containers/{{ module_id }}
## for LXD container persistent storage must be created
## Further module-specific container directories should be
## added here
## -----------------------------------------------------------

## Directories for module-specific LXD container persistent storage
## -----------------------------------------------------------------

- name: Create a directory to mount in module containers
  file:
    path: "/var/containers/{{ module_id }}"
    state: directory
    mode: '0755'


## Copy README into top-level directory for module containers

- name: Copy README
  copy:
    mode: 0644
    owner: root
    group: root
    dest: "/var/containers/{{ module_id }}/README"
    src: README
    force: yes


- name: Create a directory to mount in wellknown containers
  file:
    path: "/var/containers/{{ module_id }}/wellknown"
    state: directory
    mode: '0755'


# Example
# - name: Create a directory for <ABC> container mounts
#   file:
#     path: "/var/containers/{{ module_id }}/wellknown/<ABC>"
#     state: directory
#     mode: '0755'
