---

# Create directory for consul-template configuration files
#
- name: Create directory for consul-template configuration files
  file:
    path: /etc/consul-template
    state: directory
    mode: 0755


# Copy consul-template configuration file
#
- name: Copy consul-template configuration file
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /etc/consul-template/consul-template-config.hcl
    src: consul-template-config.hcl
    force: yes


# Copy consul-template template file for dynamic nginx configuration based on consul key-values
#
- name: Copy consul-template template file for dynamic nginx configuration
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /etc/consul-template/wellknown-sites-available.ctmpl
    src: wellknown-sites-available.ctmpl
    force: yes


# TODO Copy consul-template template file for provisioning ryo-service-proxy for wellknown
#
# - name: Copy consul-template template file for provisioning ryo-service-proxy for wellknown
#   copy:
#     mode: 0644
#     owner: root
#     group: root
#     dest: /etc/consul-template/configure-service-proxy.sh.ctmpl
#     src: configure-service-proxy.sh.ctmpl
#     force: yes


# CHECK Copy script to execute provisioning of ryo-service-proxy for wellknown
#
# - name: Copy script to execute provisioning of ryo-service-proxy for wellknown
#   copy:
#     mode: 0755
#     owner: root
#     group: root
#     dest: /usr/local/bin/execute-configure-service-proxy.sh
#     src: execute-configure-service-proxy.sh
#     force: yes


# Copy consul-template service definition
#
- name: Copy consul-template service definition
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /lib/systemd/system/consul-template.service
    src: consul-template.service
    force: yes


# Enable consul-template service
#
- name: Enable consul-template service
  service:
    name: consul-template.service
    enabled: yes
    state: stopped
