# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

#-----------------------
# REQUIRED Configuration
#-----------------------

# Basic module configuration
#---------------------------

# Do not change this unless you know what you are doing 
module_id: ryo-wellknown
